In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/ektanegi25/Credit-Card-Fraud-Detection/main/creditCardFraud_28011964_120214.csv")
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
1,50000,1,1,2,37,0,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
2,500000,1,1,2,29,0,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
3,100000,2,2,2,23,0,-1,-1,0,0,...,221,-159,567,380,601,0,581,1687,1542,0
4,140000,2,3,1,28,0,0,2,0,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0

In [3]:
df.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [4]:
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
1,50000,1,1,2,37,0,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
2,500000,1,1,2,29,0,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
3,100000,2,2,2,23,0,-1,-1,0,0,...,221,-159,567,380,601,0,581,1687,1542,0
4,140000,2,3,1,28,0,0,2,0,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT4                   1001 non-null   int64
 15  BILL_AMT5                   1001 non-null   int64
 16  BILL_AMT6                   1001 non-null   int64
 17  PAY_AMT1                    1001 non-null   int64
 18  PAY_AMT2                    1001 non-null   int64
 19  PAY_AMT3                    1001 non-null   int64
 20  PAY_AMT4                    1001 non-null   int64
 21  PAY_AMT5                    1001 non-null   int64
 22  PAY_AMT6                    1001 non-null   int64
 23  default payment next month  1001 non-null   int64
dtypes: int64(24)
memory usage: 187.8 KB

In [6]:
df.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
count,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,...,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000
mean,167532.467532,1.589411,1.776224,1.604396,34.945055,-0.004995,-0.161838,-0.164835,-0.283716,-0.283716,...,40748.408591,39078.666334,38012.011988,5382.339660,5051.400599,4176.149850,4671.488511,5331.049950,5090.704296,0.213786
std,130587.921320,0.492187,0.750916,0.532298,9.219760,1.173446,1.228732,1.262459,1.184662,1.170224,...,68206.929510,63108.238729,63074.415024,12180.755275,15626.153184,10514.647502,13269.943983,16812.536877,23658.888052,0.410183
min,10000.000000,1.000000,1.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-3684.000000,-28335.000000,-339603.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1423.000000,1206.000000,830.000000,1000.000000,390.000000,228.000000,148.000000,189.000000,0.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,17710.000000,17580.000000,15846.000000,2184.000000,1710.000000,1206.000000,1398.000000,1306.000000,1250.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,48851.000000,46404.000000,46557.000000,5090.000000,4500.000000,3720.000000,4000.000000,3745.000000,3784.000000,0.000000
max,700000.000000,2.000000,6.000000,3.000000,75.000000,8.000000,7.000000,7.000000,7.000000,7.000000,...,628699.000000,484612.000000,473944.000000,199646.000000,285138.000000,133657.000000,188840.000000,195599.000000,528666.000000,1.000000

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
LIMIT_BAL,1001.0,167532.467532,130587.921320,10000.0,50000.0,140000.0,240000.0,700000.0
SEX,1001.0,1.589411,0.492187,1.0,1.0,2.0,2.0,2.0
EDUCATION,1001.0,1.776224,0.750916,1.0,1.0,2.0,2.0,6.0
MARRIAGE,1001.0,1.604396,0.532298,0.0,1.0,2.0,2.0,3.0
AGE,1001.0,34.945055,9.219760,21.0,28.0,33.0,41.0,75.0
PAY_0,1001.0,-0.004995,1.173446,-2.0,-1.0,0.0,0.0,8.0
PAY_2,1001.0,-0.161838,1.228732,-2.0,-1.0,0.0,0.0,7.0
PAY_3,1001.0,-0.164835,1.262459,-2.0,-1.0,0.0,0.0,7.0
PAY_4,1001.0,-0.283716,1.184662,-2.0,-1.0,0.0,0.0,7.0
PAY_5,1001.0,-0.283716,1.170224,-2.0,-1.0,0.0,0.0,7.0
PAY_6,1001.0,-0.314685,1.203276,-2.0,-1.0,0.0,0.0,7.0
BILL_AMT1,1001.0,49386.738262,72657.966256,-14386.0,3128.0,21075.0,59901.0,507726.0
BILL_AMT2,1001.0,47879.345654,72090.718188,-13543.0,3274.0,20400.0,58472.0,509229.0
BILL_AMT3,1001.0,44925.682318,69545.948045,-9850.0,1940.0,19292.0,54477.0,499936.0
BILL_AMT4,1001.0,40748.408591,68206.929510,-3684.0,1423.0,17710.0,48851.0,628699.0
BILL_AMT5,1001.0,39078.666334,63108.238729,-28335.0,1206.0,17580.0,46404.0,484612.0
BILL_AMT6,1001.0,38012.011988,63074.415024,-339603.0,830.0,15846.0,46557.0,473944.0
PAY_AMT1,1001.0,5382.339660,12180.755275,0.0,1000.0,2184.0,5090.0,199646.0
PAY_AMT2,1001.0,5051.400599,15626.153184,0.0,390.0,1710.0,4500.0,285138.0
PAY_AMT3,1001.0,4176.149850,10514.647502,0.0,228.0,1206.0,3720.0,133657.0
PAY_AMT4,1001.0,4671.488511,13269.943983,0.0,148.0,1398.0,4000.0,188840.0
PAY_AMT5,1001.0,5331.049950,16812.536877,0.0,189.0,1306.0,3745.0,195599.0
PAY_AMT6,1001.0,5090.704296,23658.888052,0.0,0.0,1250.0,3784.0,528666.0
default payment next month,1001.0,0.213786,0.410183,0.0,0.0,0.0,0.0,1.0

In [8]:
!pip install pandas-profiling

Collecting pandas-profiling
  Downloading pandas_profiling-3.2.0-py2.py3-none-any.whl (262 kB)
     ---------------------------------------- 0.0/262.6 kB ? eta -:--:--
     - -------------------------------------- 10.2/262.6 kB ? eta -:--:--
     ---- -------------------------------- 30.7/262.6 kB 325.1 kB/s eta 0:00:01
     ----- ------------------------------- 41.0/262.6 kB 326.8 kB/s eta 0:00:01
     ------------ ------------------------ 92.2/262.6 kB 525.1 kB/s eta 0:00:01
     ----------------------- ------------ 174.1/262.6 kB 807.1 kB/s eta 0:00:01
     -----------------------------------  256.0/262.6 kB 983.0 kB/s eta 0:00:01
     -------------------------------------- 262.6/262.6 kB 1.0 MB/s eta 0:00:00
Collecting joblib~=1.1.0 (from pandas-profiling)
  Downloading joblib-1.1.1-py2.py3-none-any.whl (309 kB)
     ---------------------------------------- 0.0/309.8 kB ? eta -:--:--
     ------------------------------- ------ 256.0/309.8 kB 7.9 MB/s eta 0:00:01
     -------------------------------------- 309.8/309.8 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: scipy>=1.4.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (1.11.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (2.1.1)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (3.8.0)
Collecting pydantic>=1.8.1 (from pandas-profiling)
  Obtaining dependency information for pydantic>=1.8.1 from https://files.pythonhosted.org/packages/dd/b7/9aea7ee6c01fe3f3c03b8ca3c7797c866df5fecece9d6cb27caa138db2e2/pydantic-2.5.3-py3-none-any.whl.metadata
  Downloading pydantic-2.5.3-py3-none-any.whl.metadata (65 kB)
     ---------------------------------------- 0.0/65.6 kB ? eta -:--:--
     ---------------------------------------- 65.6/65.6 kB ? eta 0:00:00
Collecting PyYAML>=5.0.0 (from pandas-profiling)
  Obtaining dependency information for PyYAML>=5.0.0 from https://files.pythonhosted.org/packages/b3/34/65bb4b2d7908044963ebf614fe0fdb080773fc7030d7e39c8d3eddcd4257/PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata
  Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (3.1.3)
Requirement already satisfied: markupsafe~=2.1.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (2.1.3)
Collecting visions[type_image_path]==0.7.4 (from pandas-profiling)
  Downloading visions-0.7.4-py3-none-any.whl (102 kB)
     ---------------------------------------- 0.0/102.4 kB ? eta -:--:--
     ---------------------------------------- 102.4/102.4 kB ? eta 0:00:00
Requirement already satisfied: numpy>=1.16.0 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (1.26.0)
Collecting htmlmin>=0.1.12 (from pandas-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting missingno>=0.4.2 (from pandas-profiling)
  Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Collecting phik>=0.11.1 (from pandas-profiling)
  Obtaining dependency information for phik>=0.11.1 from https://files.pythonhosted.org/packages/95/e3/250ce99ed761389028543fcb876176ba619f6bf387d6cce3bab736bd92cc/phik-0.12.4-cp311-cp311-win_amd64.whl.metadata
  Downloading phik-0.12.4-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting tangled-up-in-unicode==0.2.0 (from pandas-profiling)
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
     ---- ----------------------------------- 0.5/4.7 MB 10.9 MB/s eta 0:00:01
     ---- ----------------------------------- 0.5/4.7 MB 10.9 MB/s eta 0:00:01
     ------- -------------------------------- 0.9/4.7 MB 6.1 MB/s eta 0:00:01
     ---------- ----------------------------- 1.3/4.7 MB 6.7 MB/s eta 0:00:01
     ------------ --------------------------- 1.5/4.7 MB 6.2 MB/s eta 0:00:01
     ---------------- ----------------------- 1.9/4.7 MB 6.9 MB/s eta 0:00:01
     ------------------ --------------------- 2.2/4.7 MB 6.6 MB/s eta 0:00:01
     ---------------------- ----------------- 2.6/4.7 MB 7.0 MB/s eta 0:00:01
     ------------------------- -------------- 3.0/4.7 MB 7.3 MB/s eta 0:00:01
     --------------------------- ------------ 3.2/4.7 MB 6.9 MB/s eta 0:00:01
     ------------------------------- -------- 3.7/4.7 MB 7.5 MB/s eta 0:00:01
     ---------------------------------- ----- 4.1/4.7 MB 7.5 MB/s eta 0:00:01
     ------------------------------------- -- 4.4/4.7 MB 7.4 MB/s eta 0:00:01
     ---------------------------------------- 4.7/4.7 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.24.0 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (2.31.0)
Collecting tqdm>=4.48.2 (from pandas-profiling)
  Obtaining dependency information for tqdm>=4.48.2 from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ---------------------------------------- 57.6/57.6 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: seaborn>=0.10.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas-profiling) (0.13.0)
Collecting multimethod>=1.4 (from pandas-profiling)
  Obtaining dependency information for multimethod>=1.4 from https://files.pythonhosted.org/packages/7f/bd/750245e47e7f307d9f94d4fa84727f4ed9956005dfa671d58be1d531a0f6/multimethod-1.10-py3-none-any.whl.metadata
  Downloading multimethod-1.10-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: attrs>=19.3.0 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (23.1.0)
Collecting networkx>=2.4 (from visions[type_image_path]==0.7.4->pandas-profiling)
  Obtaining dependency information for networkx>=2.4 from https://files.pythonhosted.org/packages/d5/f0/8fbc882ca80cf077f1b246c0e3c3465f7f415439bdea6b899f6b19f61f70/networkx-3.2.1-py3-none-any.whl.metadata
  Downloading networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting imagehash (from visions[type_image_path]==0.7.4->pandas-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
     ---------------------------------------- 0.0/296.5 kB ? eta -:--:--
     -------------------------------------- 296.5/296.5 kB 9.2 MB/s eta 0:00:00
Requirement already satisfied: Pillow in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (10.0.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2023.3)
Collecting annotated-types>=0.4.0 (from pydantic>=1.8.1->pandas-profiling)
  Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl.metadata
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.6 (from pydantic>=1.8.1->pandas-profiling)
  Obtaining dependency information for pydantic-core==2.14.6 from https://files.pythonhosted.org/packages/72/d2/fcb3bc3d6d2fa35387b57e9925f1ff5469c2da634b85061dadbd8c398545/pydantic_core-2.14.6-cp311-none-win_amd64.whl.metadata
  Downloading pydantic_core-2.14.6-cp311-none-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2023.7.22)
Requirement already satisfied: colorama in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from tqdm>=4.48.2->pandas-profiling) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\shrun\.conda\envs\butterfly\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.16.0)
Collecting PyWavelets (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling)
  Obtaining dependency information for PyWavelets from https://files.pythonhosted.org/packages/c1/c6/711bf969348053876b9d3f3826cd7a00d045178e1493ed844b630c876493/pywavelets-1.5.0-cp311-cp311-win_amd64.whl.metadata
  Downloading pywavelets-1.5.0-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Downloading multimethod-1.10-py3-none-any.whl (9.9 kB)
Downloading phik-0.12.4-cp311-cp311-win_amd64.whl (667 kB)
   ---------------------------------------- 0.0/667.1 kB ? eta -:--:--
   ------------------------------------- - 634.9/667.1 kB 13.3 MB/s eta 0:00:01
   --------------------------------------- 667.1/667.1 kB 10.4 MB/s eta 0:00:00
Downloading pydantic-2.5.3-py3-none-any.whl (381 kB)
   ---------------------------------------- 0.0/381.9 kB ? eta -:--:--
   ---------------------------------------  378.9/381.9 kB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 381.9/381.9 kB 7.9 MB/s eta 0:00:00
Downloading pydantic_core-2.14.6-cp311-none-win_amd64.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   ------------ --------------------------- 0.6/1.9 MB 12.2 MB/s eta 0:00:01
   --------------------- ------------------ 1.0/1.9 MB 10.8 MB/s eta 0:00:01
   ----------------------------- ---------- 1.4/1.9 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 10.9 MB/s eta 0:00:00
Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
   ---------------------------------------- 0.0/144.7 kB ? eta -:--:--
   ---------------------------------------- 144.7/144.7 kB 8.4 MB/s eta 0:00:00
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.3 kB ? eta -:--:--
   ---------------------------------------- 78.3/78.3 kB 4.3 MB/s eta 0:00:00
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB 8.9 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.6 MB 9.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.4/1.6 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  1.6/1.6 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 8.7 MB/s eta 0:00:00
Downloading pywavelets-1.5.0-cp311-cp311-win_amd64.whl (4.3 MB)
   ---------------------------------------- 0.0/4.3 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.3 MB 25.1 MB/s eta 0:00:01
   -------------- ------------------------- 1.5/4.3 MB 19.6 MB/s eta 0:00:01
   ---------------------- ----------------- 2.4/4.3 MB 19.2 MB/s eta 0:00:01
   -------------------------- ------------- 2.9/4.3 MB 16.6 MB/s eta 0:00:01
   ----------------------------------- ---- 3.7/4.3 MB 17.0 MB/s eta 0:00:01
   ----------------------------------- ---- 3.7/4.3 MB 17.1 MB/s eta 0:00:01
   ---------------------------------------  4.2/4.3 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------- 4.3/4.3 MB 13.6 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py): started
  Building wheel for htmlmin (setup.py): finished with status 'done'
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27092 sha256=71c02e99e384274a28268d3a5f2002b2b267dd5c9a2d7dd020c2f713651b22f5
  Stored in directory: c:\users\shrun\appdata\local\pip\cache\wheels\8d\55\1a\19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: htmlmin, tqdm, tangled-up-in-unicode, PyYAML, PyWavelets, pydantic-core, networkx, multimethod, joblib, annotated-types, pydantic, imagehash, visions, phik, missingno, pandas-profiling
  Attempting uninstall: joblib
    Found existing installation: joblib 1.3.2
    Uninstalling joblib-1.3.2:
      Successfully uninstalled joblib-1.3.2
Successfully installed PyWavelets-1.5.0 PyYAML-6.0.1 annotated-types-0.6.0 htmlmin-0.1.12 imagehash-4.3.1 joblib-1.1.1 missingno-0.5.2 multimethod-1.10 networkx-3.2.1 pandas-profiling-3.2.0 phik-0.12.4 pydantic-2.5.3 pydantic-core-2.14.6 tangled-up-in-unicode-0.2.0 tqdm-4.66.1 visions-0.7.4

In [10]:
from pandas_profiling import ProfileReport

profile = ProfileReport(df, title = "Pandas Profiling Report")
profile

c:\Users\shrun\.conda\envs\butterfly\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.5/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.5/u/import-error